### ISSUE TITLE
Create Readme

### ISSUE THREAD

**Issue by newwebash** [WriteTheDocs-SLC/Docs#4]
Our project should include a readme as this is the standard for open source projects, and to help new contributors get started.

**Comment by newwebash** [comment]
I have drafted a readme and included changes in PR #7. @KyleBlankRollins please review and make suggestions.

**Comment by KyleBlankRollins** [comment]
I went ahead and merged PR #7. I'll look at adding to it a bit in the future.

**Comment by KyleBlankRollins** [comment]
I just updated the Readme with some tools info. Also changed the file type from .txt to .md.

I plan to add more detail and I believe we talked about adding a license? Maybe it'll be a research task for us to figure out what license is most appropriate?
